# Generated by Django 4.2.16 on 2026-06-25 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('db_type', models.CharField(choices=[('ORACLE', 'Oracle'), ('POSTGRES', 'PostgreSQL'), ('SQLSERVER', 'SQL Server')], max_length=20)),
                ('host', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField()),
                ('database_name', models.CharField(blank=True, max_length=255)),
                ('service_name', models.CharField(blank=True, max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('options_json', models.TextField(blank=True, help_text='Optional JSON for extra driver options')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('test_type', models.CharField(choices=[('CONNECTION', 'DB Connection'), ('TABLE_EXISTS', 'Table Exists'), ('ROW_COUNT', 'Row Count'), ('QUERY_VALUE', 'Query Value')], max_length=30)),
                ('table_name', models.CharField(blank=True, max_length=255)),
                ('query', models.TextField(blank=True)),
                ('expected_value', models.CharField(blank=True, max_length=255)),
                ('comparison_operator', models.CharField(choices=[('=', '='), ('>', '>'), ('>=', '>='), ('<', '<'), ('<=', '<='), ('contains', 'contains')], default='=', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='db_testcases.databaseconnection')),
            ],
        ),
        migrations.CreateModel(
            name='TestExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('ERROR', 'Error')], max_length=10)),
                ('details', models.TextField(blank=True)),
                ('actual_value', models.TextField(blank=True)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='db_testcases.testcase')),
            ],
            options={
                'ordering': ['-executed_at'],
            },
        ),
    ]

