# Generated by Django 4.2.16 on 2026-06-25 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('db_testcases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('primary_color', models.CharField(default='#0f766e', max_length=20)),
                ('accent_color', models.CharField(default='#f59e0b', max_length=20)),
                ('background_color', models.CharField(default='#f3f7f5', max_length=20)),
                ('surface_color', models.CharField(default='#ffffff', max_length=20)),
                ('text_color', models.CharField(default='#122322', max_length=20)),
                ('border_color', models.CharField(default='#d7e2df', max_length=20)),
                ('sidebar_start_color', models.CharField(default='#0b2d2a', max_length=20)),
                ('sidebar_end_color', models.CharField(default='#133734', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserThemePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='db_testcases.theme')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]

