# Generated by Django 4.2.16 on 2026-06-25 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_testcases', '0002_theme_userthemepreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ProjectFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='db_testcases.projectfolder')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'unique_together': {('parent', 'name')},
            },
        ),
        migrations.AddField(
            model_name='testcase',
            name='project_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_cases', to='db_testcases.projectfolder'),
        ),
    ]

