# Generated by Django 6.0.6 on 2026-06-27 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_testcases', '0004_userprofile_auditlog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='db_testcase_user_id_f2cc78_idx',
            old_name='testcases_a_user_id_fb4eae_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='db_testcase_target__6b7d60_idx',
            old_name='testcases_a_target__996a22_idx',
        ),
    ]
