# Generated by Django 6.0.2 on 2026-03-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('value', models.TextField(default='')),
                ('label', models.CharField(default='', max_length=200)),
                ('description', models.TextField(default='')),
                ('group_name', models.CharField(default='General', max_length=100)),
                ('input_type', models.CharField(default='text', max_length=20)),
                ('choices', models.TextField(default='')),
            ],
            options={
                'db_table': 'app_config',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DataEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.UUIDField()),
                ('step_no', models.IntegerField()),
                ('field_name', models.TextField(blank=True, null=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'data',
                'ordering': ['step_no'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Locator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.UUIDField()),
                ('step_no', models.IntegerField()),
                ('strategy', models.TextField()),
                ('locator', models.TextField()),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'locators',
                'ordering': ['step_no'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.UUIDField()),
                ('step_no', models.IntegerField()),
                ('action', models.TextField()),
                ('page_url', models.TextField()),
                ('element_tag', models.TextField(blank=True, null=True)),
                ('locator_id', models.BigIntegerField(blank=True, null=True)),
                ('data_id', models.BigIntegerField(blank=True, null=True)),
                ('raw_event', models.JSONField()),
                ('created_at', models.DateTimeField()),
                ('recorder', models.TextField(blank=True, null=True)),
                ('runner', models.TextField(blank=True, null=True)),
                ('folder_name', models.TextField(blank=True, null=True)),
                ('headless_state', models.BooleanField(default=False)),
                ('file_order', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'recordings',
                'ordering': ['step_no'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RemoteExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=150, null=True)),
                ('remote_ip', models.CharField(max_length=255)),
                ('remote_port', models.IntegerField(default=8888)),
                ('record_id', models.UUIDField(blank=True, null=True)),
                ('headless', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'remote_executions',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RunResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.UUIDField()),
                ('record_id', models.UUIDField()),
                ('step_no', models.IntegerField()),
                ('action', models.TextField()),
                ('page_url', models.TextField()),
                ('element_tag', models.TextField(blank=True, null=True)),
                ('locator_id', models.BigIntegerField(blank=True, null=True)),
                ('data_id', models.BigIntegerField(blank=True, null=True)),
                ('raw_event', models.JSONField()),
                ('status', models.TextField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('not_executed', 'Not Executed')], default='not_executed')),
                ('message', models.TextField(blank=True, null=True)),
                ('runner', models.TextField(blank=True, null=True)),
                ('author', models.TextField(blank=True, null=True)),
                ('folder_name', models.TextField(blank=True, null=True)),
                ('parent_folder_id', models.UUIDField(blank=True, null=True)),
                ('sub_folder_id', models.UUIDField(blank=True, null=True)),
                ('end_folder_id', models.UUIDField(blank=True, null=True)),
                ('run_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'run_table',
                'ordering': ['run_id', 'step_no'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SessionMeta',
            fields=[
                ('record_id', models.UUIDField(primary_key=True, serialize=False)),
                ('record_name', models.TextField(default='')),
                ('recorder', models.TextField(blank=True, null=True)),
                ('folder_name', models.TextField(blank=True, null=True)),
                ('parent_folder_id', models.UUIDField(blank=True, null=True)),
                ('sub_folder_id', models.UUIDField(blank=True, null=True)),
                ('end_folder_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'session_meta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.UUIDField()),
                ('step_no', models.IntegerField()),
                ('action', models.TextField()),
                ('page_url', models.TextField()),
                ('element_tag', models.TextField(blank=True, null=True)),
                ('locator_id', models.BigIntegerField(blank=True, null=True)),
                ('data_id', models.BigIntegerField(blank=True, null=True)),
                ('raw_event', models.JSONField()),
                ('created_at', models.DateTimeField()),
                ('recorder', models.TextField(blank=True, null=True)),
                ('runner', models.TextField(blank=True, null=True)),
                ('author', models.TextField(blank=True, null=True)),
                ('folder_name', models.TextField(blank=True, null=True)),
                ('headless_state', models.BooleanField(default=False)),
                ('file_order', models.IntegerField(default=1)),
                ('parent_folder_id', models.UUIDField(blank=True, null=True)),
                ('sub_folder_id', models.UUIDField(blank=True, null=True)),
                ('end_folder_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'steps',
                'ordering': ['step_no'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RemoteTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_ip', models.CharField(max_length=255)),
                ('remote_port', models.IntegerField(default=8888)),
                ('last_used', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'remote_targets',
                'ordering': ['-last_used'],
                'unique_together': {('remote_ip', 'remote_port')},
            },
        ),
    ]
