# Generated by Django 4.2.30 on 2026-06-16 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('base_url', models.URLField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('auth_type', models.CharField(choices=[('none', 'None'), ('basic', 'Basic Auth'), ('bearer', 'Bearer Token'), ('api_key', 'API Key')], default='none', max_length=20)),
                ('auth_credentials', models.TextField(blank=True, help_text='JSON-formatted credentials')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='environments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('module', models.CharField(blank=True, help_text='Module or API group', max_length=100)),
                ('project', models.CharField(blank=True, help_text='Project name', max_length=100)),
                ('endpoint', models.CharField(help_text='API endpoint path (relative to base URL)', max_length=1000)),
                ('http_method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], default='GET', max_length=7)),
                ('headers', models.TextField(blank=True, default='{}', help_text='JSON-formatted headers')),
                ('query_params', models.TextField(blank=True, default='{}', help_text='JSON-formatted query parameters')),
                ('path_params', models.TextField(blank=True, default='{}', help_text='JSON-formatted path parameters')),
                ('request_body', models.TextField(blank=True, help_text='Request body (JSON or raw text)')),
                ('auth_type', models.CharField(choices=[('none', 'None'), ('inherit', 'Inherit from Environment'), ('basic', 'Basic Auth'), ('bearer', 'Bearer Token'), ('api_key', 'API Key')], default='inherit', max_length=10)),
                ('auth_credentials', models.TextField(blank=True, help_text='JSON-formatted auth credentials')),
                ('expected_status_code', models.IntegerField(blank=True, null=True)),
                ('expected_response_content', models.TextField(blank=True, help_text='Expected content in response body')),
                ('expected_response_time_ms', models.IntegerField(blank=True, help_text='Max acceptable response time in ms', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('tester', 'Tester'), ('viewer', 'Viewer')], default='tester', max_length=10)),
                ('is_active_profile', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('result_status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('error', 'Error')], max_length=10)),
                ('request_url', models.TextField(blank=True)),
                ('request_headers', models.TextField(blank=True)),
                ('request_body', models.TextField(blank=True)),
                ('response_status_code', models.IntegerField(null=True)),
                ('response_headers', models.TextField(blank=True)),
                ('response_body', models.TextField(blank=True)),
                ('response_time_ms', models.IntegerField(null=True)),
                ('status_code_match', models.BooleanField(null=True)),
                ('content_match', models.BooleanField(null=True)),
                ('time_within_threshold', models.BooleanField(null=True)),
                ('error_message', models.TextField(blank=True)),
                ('environment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='api_testcases.environment')),
                ('executed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to=settings.AUTH_USER_MODEL)),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='api_testcases.testcase')),
            ],
            options={
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('testcase_create', 'Test Case Created'), ('testcase_update', 'Test Case Updated'), ('testcase_delete', 'Test Case Deleted'), ('testcase_execute', 'Test Case Executed'), ('environment_create', 'Environment Created'), ('environment_update', 'Environment Updated'), ('environment_delete', 'Environment Deleted'), ('user_create', 'User Created'), ('user_update', 'User Updated'), ('user_deactivate', 'User Deactivated')], max_length=30)),
                ('target_type', models.CharField(blank=True, max_length=50)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('details', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]

