# Generated by Django 4.2.30 on 2026-06-16 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_testcases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('source_file', models.CharField(blank=True, help_text='Original uploaded filename', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_modules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ModuleEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Request/operation name', max_length=255)),
                ('http_method', models.CharField(default='GET', max_length=7)),
                ('endpoint_path', models.CharField(help_text='API endpoint path', max_length=1000)),
                ('headers', models.TextField(blank=True, default='{}')),
                ('request_body', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoints', to='api_testcases.apimodule')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]

