# Generated by Django 4.2.30 on 2026-06-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_testcases', '0002_apimodule_moduleendpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleendpoint',
            name='default_payload',
            field=models.TextField(blank=True, help_text='Default payload JSON for this endpoint'),
        ),
        migrations.AddField(
            model_name='moduleendpoint',
            name='expected_responses',
            field=models.TextField(blank=True, default='{}', help_text='JSON map of status_code -> sample response body'),
        ),
    ]

