# Generated by Django 4.2.30 on 2026-06-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_testcases', '0003_moduleendpoint_default_payload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apimodule',
            name='base_path',
            field=models.CharField(blank=True, help_text='Base URL path for this API module', max_length=1000),
        ),
    ]

