# Generated by Django 4.2.30 on 2026-06-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_testcases', '0004_apimodule_base_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='apimodule',
            name='module_auth_type',
            field=models.CharField(choices=[('none', 'None'), ('oauth2', 'OAuth 2.0')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='apimodule',
            name='oauth2_add_to',
            field=models.CharField(choices=[('request_headers', 'Request Headers'), ('request_url', 'Request URL')], default='request_headers', max_length=20),
        ),
        migrations.AddField(
            model_name='apimodule',
            name='oauth2_client_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='apimodule',
            name='oauth2_client_secret',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='apimodule',
            name='oauth2_current_token',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='apimodule',
            name='oauth2_header_prefix',
            field=models.CharField(default='Bearer', max_length=50),
        ),
        migrations.AddField(
            model_name='apimodule',
            name='oauth2_token_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apimodule',
            name='oauth2_token_url',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]

