# Generated by Django 4.2.30 on 2026-06-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_testcases', '0005_apimodule_oauth2_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='base_url',
            field=models.CharField(max_length=500),
        ),
    ]

