# Generated by Django 5.2 on 2026-06-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_testcases', '0007_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='form_data',
            field=models.TextField(blank=True, default='[]', help_text='JSON array of form-data rows [{type, key, value, description}]'),
        ),
        migrations.AlterField(
            model_name='environment',
            name='auth_type',
            field=models.CharField(choices=[('none', 'None'), ('basic', 'Basic Auth'), ('bearer', 'Bearer Token'), ('oauth2', 'OAuth 2.0'), ('api_key', 'API Key')], default='none', max_length=20),
        ),
    ]

