# Generated by Django 6.0.6 on 2026-06-27 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_testcases', '0010_order_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='auth_type',
            field=models.CharField(choices=[('none', 'None'), ('basic', 'Basic Auth'), ('digest', 'Digest Auth'), ('bearer', 'Bearer Token'), ('oauth2', 'OAuth 2.0'), ('api_key', 'API Key'), ('oauth1', 'OAuth 1.0'), ('awsv4', 'AWS Signature'), ('ntlm', 'NTLM Auth')], default='none', max_length=20),
        ),
    ]
